#!/usr/bin/env bash

SCRIPT_FOLDER="$(dirname "$(realpath "${BASH_SOURCE[0]}")")"
cd $SCRIPT_FOLDER
cd ..
generatefile="projects/meta.json"
if [[ -f $generatefile ]]; then
  rm $generatefile
fi

processToml() {
  echo "  {"
  while read -r line; do
    key=$(echo $line | grep -o "^..\+=" | grep -o "[^=]\+" | sed -e 's/^[[:space:]]*//; s/[[:space:]]*$//' -e 's/\(.*\)/"\1"/')
    value=$(echo $line | grep -o "=.\+" | grep -o "[^=]\+" | sed -e 's/^[[:space:]]*//; s/[[:space:]]*$//' -e 's/\(.*\)/"\1"/')
    echo "     $key : $value,"
  done <$1
  echo "     \"page\" : \"$(echo $1 | sed -e "s/meta\.toml/index\.html/")\""
  echo "  },"
}

processMetaToml() {
  echo "["
  find projects -type f -regex 'projects/[^/]*/meta\.toml' | while read -r file; do
    processToml $file
  done
}

generateJson() {
  processMetaToml | head -n -1
  echo "  }"
  echo "]"
}

generateJson >$generatefile
